targetScope = 'resourceGroup'

import { GovernanceTags } from './monitoring-environment.bicep'

// New-server preparation only. The inline Entra administrator is create-time
// configuration, not an update path for an existing server.
// https://learn.microsoft.com/azure/azure-sql/database/authentication-azure-ad-only-authentication-create-server
// Public networking does not grant SQL access: Entra users and SQL roles still apply.
// https://learn.microsoft.com/azure/azure-sql/database/firewall-configure

type SqlFirewallRule = {
  name: string
  startIpAddress: string
  endIpAddress: string
}

@description('Globally unique NEW logical server name. No SQL administrator credentials are supplied or generated by this template.')
@minLength(1)
@maxLength(63)
param sqlServerName string

@description('Azure public-cloud region for the new SQL server and its databases.')
@minLength(1)
param location string

param tags GovernanceTags

@description('The single application database for all durable state. The optional isolated proof catalog appends -proof.')
@minLength(1)
@maxLength(122)
param databaseName string

@description('Initial small always-on tier. S1 is a starting size, not a measured capacity guarantee.')
@allowed([
  'S0'
  'S1'
  'S2'
  'S3'
])
param databaseSkuName string = 'S1'

@description('Application data-file limit in GiB, within the storage included by these Standard tiers.')
@minValue(1)
@maxValue(250)
param databaseMaxSizeGiB int = 10

@description('Create a temporary Basic/5-DTU/2-GiB proof database. It receives no application users or grants from this template.')
param enableProofDatabase bool = false

@description('Operator-selected Entra SQL administrator display name. This is not a Command Center app role.')
@minLength(1)
param entraAdminDisplayName string

@description('Directory object ID of the operator-selected Entra user or security group. Never an app-role ID or client ID.')
@minLength(36)
@maxLength(36)
param entraAdminObjectId string

@allowed([
  'Group'
  'User'
])
param entraAdminPrincipalType string = 'Group'

@description('Tenant containing the selected SQL administrator; must match the deployment subscription tenant.')
@minLength(36)
@maxLength(36)
param tenantId string

@description('Existing Log Analytics workspace resource ID. Auditing uses Azure Monitor, not storage credentials.')
@minLength(1)
param logAnalyticsWorkspaceResourceId string

@description('Admit Azure-hosted callers through the SQL firewall. The special 0.0.0.0 rule includes other Azure subscriptions; Entra-only authentication and least-privilege SQL users remain required.')
param allowAzureServices bool = true

@description('Optional explicit IPv4 client firewall rules. No Internet-wide range is created by default.')
@maxLength(255)
param clientFirewallRules SqlFirewallRule[] = []

@description('Optional, separately reviewed network-policy exception tags on this logical server only. Empty for ordinary customer deployments; tenant-specific exemptions can expire.')
param sqlNetworkExceptionTags object = {}

var dtuCapacity = {
  S0: 10
  S1: 20
  S2: 50
  S3: 100
}

// NVARCHAR retains UTF-16 bytes under this collation. The SQL kernel explicitly
// uses BIN2 for authority comparisons and UTF8 only for its separate API hashes.
var databaseCollation = 'SQL_Latin1_General_CP1_CI_AS'
var proofDatabaseName = '${databaseName}-proof'

resource sqlServer 'Microsoft.Sql/servers@2023-08-01' = {
  name: sqlServerName
  location: location
  tags: union(sqlNetworkExceptionTags, tags)
  properties: {
    version: '12.0'
    minimalTlsVersion: '1.2'
    publicNetworkAccess: 'Enabled'
    administrators: {
      administratorType: 'ActiveDirectory'
      azureADOnlyAuthentication: true
      login: entraAdminDisplayName
      principalType: entraAdminPrincipalType
      sid: entraAdminObjectId
      tenantId: tenantId
    }
  }
}

// Proxy uses TCP 1433 for public clients. Redirect has additional port requirements.
resource connectionPolicy 'Microsoft.Sql/servers/connectionPolicies@2023-08-01' = {
  parent: sqlServer
  name: 'default'
  properties: {
    connectionType: 'Proxy'
  }
}

resource masterDatabase 'Microsoft.Sql/servers/databases@2023-08-01' existing = {
  parent: sqlServer
  name: 'master'
}

// Server auditing routes through master, not a diagnostic setting on the server.
// These extension/configuration resource types do not support tags.
resource auditDiagnostics 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: '${sqlServerName}-audit'
  scope: masterDatabase
  properties: {
    workspaceId: logAnalyticsWorkspaceResourceId
    logs: [
      {
        category: 'SQLSecurityAuditEvents'
        enabled: true
      }
    ]
  }
}

resource serverAudit 'Microsoft.Sql/servers/auditingSettings@2023-08-01' = {
  parent: sqlServer
  name: 'default'
  properties: {
    state: 'Enabled'
    isAzureMonitorTargetEnabled: true
    auditActionsAndGroups: [
      'SUCCESSFUL_DATABASE_AUTHENTICATION_GROUP'
      'FAILED_DATABASE_AUTHENTICATION_GROUP'
      'BATCH_COMPLETED_GROUP'
    ]
  }
  dependsOn: [
    auditDiagnostics
  ]
}

resource applicationDatabase 'Microsoft.Sql/servers/databases@2023-08-01' = {
  parent: sqlServer
  name: databaseName
  location: location
  tags: tags
  sku: {
    name: databaseSkuName
    tier: 'Standard'
    capacity: dtuCapacity[databaseSkuName]
  }
  properties: {
    createMode: 'Default'
    collation: databaseCollation
    catalogCollation: 'DATABASE_DEFAULT'
    maxSizeBytes: databaseMaxSizeGiB * 1024 * 1024 * 1024
    requestedBackupStorageRedundancy: 'Local'
    zoneRedundant: false
    readScale: 'Disabled'
    isLedgerOn: false
  }
  dependsOn: [
    serverAudit
    connectionPolicy
  ]
}

resource applicationBackups 'Microsoft.Sql/servers/databases/backupShortTermRetentionPolicies@2023-08-01' = {
  parent: applicationDatabase
  name: 'default'
  properties: {
    retentionDays: 7
    diffBackupIntervalInHours: 24
  }
}

resource applicationEncryption 'Microsoft.Sql/servers/databases/transparentDataEncryption@2023-08-01' = {
  parent: applicationDatabase
  name: 'current'
  properties: {
    state: 'Enabled'
  }
}

resource proofDatabase 'Microsoft.Sql/servers/databases@2023-08-01' = if (enableProofDatabase) {
  parent: sqlServer
  name: proofDatabaseName
  location: location
  tags: tags
  sku: {
    name: 'Basic'
    tier: 'Basic'
    capacity: 5
  }
  properties: {
    createMode: 'Default'
    collation: databaseCollation
    catalogCollation: 'DATABASE_DEFAULT'
    maxSizeBytes: 2147483648
    requestedBackupStorageRedundancy: 'Local'
    zoneRedundant: false
    readScale: 'Disabled'
    isLedgerOn: false
  }
  dependsOn: [
    serverAudit
    connectionPolicy
  ]
}

resource proofBackups 'Microsoft.Sql/servers/databases/backupShortTermRetentionPolicies@2023-08-01' = if (enableProofDatabase) {
  parent: proofDatabase
  name: 'default'
  properties: {
    retentionDays: 7
    diffBackupIntervalInHours: 24
  }
}

resource proofEncryption 'Microsoft.Sql/servers/databases/transparentDataEncryption@2023-08-01' = if (enableProofDatabase) {
  parent: proofDatabase
  name: 'current'
  properties: {
    state: 'Enabled'
  }
}

resource azureServicesFirewallRule 'Microsoft.Sql/servers/firewallRules@2023-08-01' = if (allowAzureServices) {
  parent: sqlServer
  name: 'AllowAzureServices'
  properties: {
    startIpAddress: '0.0.0.0'
    endIpAddress: '0.0.0.0'
  }
  dependsOn: [
    serverAudit
    connectionPolicy
  ]
}

resource clientRules 'Microsoft.Sql/servers/firewallRules@2023-08-01' = [for rule in clientFirewallRules: {
  parent: sqlServer
  name: rule.name
  properties: {
    startIpAddress: rule.startIpAddress
    endIpAddress: rule.endIpAddress
  }
  dependsOn: [
    serverAudit
    connectionPolicy
  ]
}]

output azureSqlServer string = sqlServer.properties.fullyQualifiedDomainName
output azureSqlDatabase string = applicationDatabase.name
output sqlServerResourceId string = sqlServer.id
output applicationDatabaseResourceId string = applicationDatabase.id
output proofDatabaseResourceId string = enableProofDatabase ? proofDatabase.id : ''
output azureSqlProofDatabase string = enableProofDatabase ? proofDatabaseName : ''
output azureServicesFirewallEnabled bool = allowAzureServices
output auditDiagnosticSettingResourceId string = auditDiagnostics.id

@description('ARM has no database compatibilityLevel property. The deployment owner must set and verify this level through Entra-authenticated SQL before schema bootstrap; runtime identities must not do it.')
output requiredCompatibilityLevel int = 160

@description('Provisioning does not prove controller hosting, DNS, TCP, Entra login or SQL grants. Verify every actual caller before cutover.')
output liveAcceptanceRequired bool = true
